spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

  cloud:
    stream:
      default:
        consumer:
          use-native-encoding: true
        producer:
          use-native-encoding: true
      bindings:
        transaction-done-output:
          destination: transaction-done
      kafka:
        binder:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer

  kafka:
    bootstrap-servers: 0.0.0.0:9092
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name:
    producer: transaction.donet

auto:
  create:
    topics:
      enable: true
